vich_uploader:
    db_driver: orm

    mappings:
        project_image:
            uri_prefix: '%app.path.project_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.project_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        project_files:
            uri_prefix: '%app.path.project_files%'
            upload_destination: '%kernel.project_dir%/public%app.path.project_files%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer